arrowParens: avoid
bracketSameLine: true
bracketSpacing: true
endOfLine: auto
importOrder:
  - '^react$|^styled-components'
  - '<THIRD_PARTY_MODULES>'
  - '<THIRD_PARTY_TS_TYPES>'
  - '<TS_TYPES>'
  - '^[./]'
importOrderSeparation: true
importOrderSortSpecifiers: true
jsxSingleQuote: true
plugins:
  - '@trivago/prettier-plugin-sort-imports'
printWidth: 120
proseWrap: 'always'
quoteProps: as-needed
semi: true
singleQuote: true
tabWidth: 2
trailingComma: 'all'
