bracketSpacing: true
plugins:
  - "@trivago/prettier-plugin-sort-imports"
printWidth: 120
proseWrap: "always"
singleQuote: false
tabWidth: 2
trailingComma: "all"

overrides:
  - files: ["*.d.ts", "*.ts", "*.tsx"]
    options:
      importOrder:
        - "^react$|^styled-components"
        - "<THIRD_PARTY_MODULES>"
        - "<THIRD_PARTY_TS_TYPES>"
        - "<TS_TYPES>"
        - "^[./]"
      importOrderSeparation: false
      importOrderSortSpecifiers: true
